#!/usr/bin/env bash
# This script displays the story of the file /etc/passwd.
file="/etc/passwd"
while read -r line; do
	USERNAME=$(echo "$line" | cut -d ":" -f1)
    GROUP_ID=$(echo "$line" | cut -d ":" -f4)
	HOME_DIRECTORY=$(echo "$line" | cut -d ":" -f6)
	COMMAND_SHELL=$(echo "$line" | cut -d ":" -f7)
	USER_ID=$(echo "$line" | cut -d ":" -f3)
	PASSWORD=$(echo "$line" | cut -d ":" -f2)
	USER_ID_INFO=$(echo "$line" | cut -d ":" -f5)
	echo -n "The user $USERNAME is part of the $GROUP_ID gang,"
	echo -n " lives in $HOME_DIRECTORY and rides $COMMAND_SHELL."
	echo -n " $USER_ID's place is protected by the passcode $PASSWORD,"
	echo " more info about the user here: $USER_ID_INFO"
done < "$file"
