#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, good luck in line 8, bad luck in line 4
i=1
while [ $i -le 10 ]
do
	if [[ $i = 4 ]]
	then echo "bad luck"
	elif [[ $i = 8 ]]
	then echo "good luck"
	else
	echo "Best School"
	fi
	((i++))
done
